#!/bin/bash
echo "Installing Choreographer Dependencies"

if command -v cpanm >/dev/null 2>&1
then
echo "cpanm found"
else
curl -L http://cpanmin.us | perl - --sudo App::cpanminus
fi

if command -v carton >/dev/null 2>&1
then
echo "Carton found"
else 
sudo cpanm carton
fi

echo "Done"
