#!/usr/bin/perl

eval 'exec /usr/bin/perl  -S $0 ${1+"$@"}'
    if 0; # not running under some shell

use lib 'local/lib/perl5'; # TODO: Convert to local::lib
use lib 'lib';

use strict;
use warnings;

use 5.008001;
use Dancer::Choreographer::CLI;

exit Dancer::Choreographer::CLI->new->run(@ARGV);

__END__

=head1 NAME

choreographer - An opinionated scaffolding tool for Dancer Applications.

=head1 SYNOPSIS

  > choreographer init
  > choreographer

=head1 Commands

=head2 init

Initiallize an existing Dancer directory applying Choreographers standards.

When run without a command, choreographer defaults to 'init'

=head2 new [name]

This command creates a Dancer app and applies Choreographer to that.

=head2 add model [name]

This command creates a new model in the current project. You must be in the base directory of the project for it to work.

The 

=head1 JSON Format

Example Json
'[
          {
            "models" : [
                          {
                            "readable_name" : "Test",
                            "write_file" : 1,
                            "table_name" : "test",
                            "attributes" : [
                                              {
                                                "inline" : 0,
                                                "options" : [],
                                                "order" : "0",
                                                "static_label" : 0,
                                                "type" : "text",
                                                "label" : "Test",
                                                "max_length" : 32,
                                                "mandatory" : 0
                                              },
                                              {
                                                "inline" : 0,
                                                "options" : [],
                                                "order" : "1",
                                                "static_label" : 0,
                                                "type" : "email",
                                                "label" : "Email",
                                                "max_length" : 64,
                                                "mandatory" : 0
                                              },
                                              {
                                                "inline" : 0,
                                                "options" : [
                                                               "Male",
                                                               "Female"
                                                             ],
                                                "order" : "2",
                                                "static_label" : 0,
                                                "type" : "radio",
                                                "label" : "Gender",
                                                "mandatory" : 1,
                                                "max_length" : 16
                                              }
                                            ],
                            "overlay" : ""
                          }
                        ],
            "settings" : {
                            "app_path" : "/Users/seanzellmer/Apps/Demo/",
                            "app_name" : "Demo",
                            "write_files" : 1,
                            "overwrite" : 1,
                            "module_only": 1
                          }
          }
        ]'

=head1 DESCRIPTION

For more documentation, refer to L<Dancer::Choreographer> by running C<perldoc Dancer::Choreographer> or C<choreographer --help>.

=head1 SEE ALSO

L<Dancer::Choreographer>

=cut
